//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Club_Sport_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonner()
        {
            this.paiments = new HashSet<paiment>();
        }
    
        public int codeAb { get; set; }
        public Nullable<int> CodeTAb { get; set; }
        public Nullable<int> DureeAb { get; set; }
        public Nullable<int> NumA { get; set; }
    
        public virtual Type_abonnement Type_abonnement { get; set; }
        public virtual Adherent Adherent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paiment> paiments { get; set; }
    }
}
