//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Club_Sport_Final
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GCS_FinalEntities1 : DbContext
    {
        public GCS_FinalEntities1()
            : base("name=GCS_FinalEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonner> Abonners { get; set; }
        public virtual DbSet<Activite> Activites { get; set; }
        public virtual DbSet<Adherent> Adherents { get; set; }
        public virtual DbSet<Créneau> Créneau { get; set; }
        public virtual DbSet<Entraineur> Entraineurs { get; set; }
        public virtual DbSet<Groupe> Groupes { get; set; }
        public virtual DbSet<jour> jours { get; set; }
        public virtual DbSet<paiment> paiments { get; set; }
        public virtual DbSet<Salle> Salles { get; set; }
        public virtual DbSet<seance> seances { get; set; }
        public virtual DbSet<Type_abonnement> Type_abonnement { get; set; }
    }
}
