//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Club_Sport_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class paiment
    {
        public int CodeAb { get; set; }
        public int NumA { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public string ModeP { get; set; }
    
        public virtual Abonner Abonner { get; set; }
        public virtual Adherent Adherent { get; set; }
    }
}
